create table Import.events
(
    id,
    name,
    deadline_time,
    average_entry_score,
    finished,
    data_checked,
    highest_scoring_entry,
    deadline_time_epoch,
    deadline_time_game_offset,
    highest_score,
    is_previous,
    is_current,
    is_next,
    chip_plays,
    most_selected,
    most_transferred_in,
    top_element,
    top_element_info,
    transfers_made,
    most_captained,
    most_vice_captained
);